// Builds src/lib/blockSprites.ts (block id -> data URL) from the hand-captured
// images in gallery/manual/. One enemy capture per size is shared across its
// same-size variants.

const BLOCK_IDS = [
  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22,
  23, 24, 25, 26, 27, 28, 29, 31, 32, 33, 34, 35, 40, 41, 42, 45, 46, 47, 48, 49,
  50, 51, 52, 53, 54, 55, 56,
];

const ENEMY_GROUPS: { ids: number[] }[] = [
  { ids: [30, 36, 37] }, // small
  { ids: [38, 39] }, // medium
  { ids: [43, 44] }, // big
];

async function embed(id: number): Promise<string | null> {
  const path = `gallery/manual/block_${id}.png`;
  if (!(await Bun.file(path).exists())) return null;
  const bytes = Buffer.from(await Bun.file(path).arrayBuffer());
  return "data:image/png;base64," + bytes.toString("base64");
}

const sprites: Record<number, string> = {};
const missing: number[] = [];

for (const id of BLOCK_IDS) {
  const url = await embed(id);
  if (url) sprites[id] = url;
  else missing.push(id);
}

for (const grp of ENEMY_GROUPS) {
  // First captured id in the group represents the whole size.
  let groupUrl: string | null = null;
  for (const id of grp.ids) {
    const url = await embed(id);
    if (url) {
      groupUrl = url;
      break;
    }
  }
  if (!groupUrl) {
    missing.push(...grp.ids);
    continue;
  }
  for (const id of grp.ids) {
    sprites[id] = (await embed(id)) ?? groupUrl;
  }
}

const ids = Object.keys(sprites).map(Number).sort((a, b) => a - b);
const entries = ids.map(id => `  ${id}: "${sprites[id]}",`).join("\n");
const module = `// AUTO-GENERATED by scripts/gen-sprites.ts — do not edit by hand.
// Real block sprites captured from the game, keyed by block id (data URLs).

export const BLOCK_SPRITES: Record<number, string> = {
${entries}
};
`;
await Bun.write("src/lib/blockSprites.ts", module);

console.log(`Wrote src/lib/blockSprites.ts — ${ids.length} sprites`);
if (missing.length) console.log(`  missing captures for ids: ${missing.join(", ")}`);
